spring:
  datasource:
    url: jdbc:mysql://localhost:3307/er_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

output:
  dir: output